### ISSUE TITLE
Problems with running the test

### ISSUE THREAD

**Issue by baartch** [CommonsSwarm/hatch-template#4]
Hi everyone

Today I tried to run the tests. The first one passes, but the following three don't.
I get the output you see below. With debuging I figured out it is caused by the `hatchContext.hatchUser` being undefined, while `hatchContext` is defined. You can see this in the _Debug Console_ on the screenshot.
Someone any idea what I'm doing wrong? Thanks for your help!!

![image](https://user-images.githubusercontent.com/26668031/112669944-99024700-8e60-11eb-8e4a-478db3f55a40.png)

```yarn run v1.22.5
$ yarn workspace @scaffold-eth/hardhat test --network localhost
$ hardhat test --network localhost
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Every 5s a new block is mined in localhost.


  Hatch Flow
Tx one completed: Hatch DAO (0xdC09dF99bB809401b2637171A45d39087c2081ed) created. Dandelion Voting and Hooked Token Manager set up.
Tx two completed: Impact Hours app and Hatch app set up.
Tx three completed: Tollgate, Redemptions and Conviction Voting apps set up.
    When max goal is reached
      ✓ opens the hatch (778ms)
      1) contributes with a max goal amount to the hatch
      2) claims the impact hours for all contributors
      3) closes the hatch


  1 passing (3m)
  3 failing

  1) Hatch Flow
       When max goal is reached
         contributes with a max goal amount to the hatch:
     TypeError: Cannot read property 'getAddress' of undefined
      at Context.<anonymous> (test/hatch.ts:34:108)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Hatch Flow
       When max goal is reached
         claims the impact hours for all contributors:
     ProviderError: VM Exception while processing transaction: revert IH_HATCH_NOT_GOAL_REACHED
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at GanacheGasMultiplierProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:170:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Hatch Flow
       When max goal is reached
         closes the hatch:
     ProviderError: VM Exception while processing transaction: revert ERROR_IMPACT_HOURS_NOT_FULLY_CLAIMED
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at GanacheGasMultiplierProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:170:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 3
Command: /home/andy/miniconda3/envs/tec-lab/bin/node
Arguments: /usr/share/yarn/lib/cli.js test --network localhost
Directory: /home/andy/dev/gitrepos/TEC/hatch-template/packages/hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by sembrestels** [comment]
You are probably running the tests in master, I think it should be fixed by #7.

**Comment by sembrestels** [comment]
It should work now.

**Comment by baartch** [comment]
Awesome. Now all tests complete successful. Thank you
